# Generated by Django 5.2.4 on 2025-08-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
